### ISSUE TITLE
Augeas lens from rodjek/puppet-haproxy?

### ISSUE THREAD

**Issue by antaflos** [puppetlabs/puppetlabs-haproxy#62]
Is it at all feasible to think about migrating from the current way of generating `haproxy.cfg` (using concat and lots of hashes and arrays) to using rodjek's Augeas lens from https://github.com/rodjek/puppet-haproxy?

The advantages would be the ones listed in https://github.com/rodjek/puppet-haproxy/blob/master/README.md.

Would this allow to keep the current interface where one can just supply arrays and hashes of options via `default_options`, `global_options` and `options`? Doesn't seem like it to me.

But what would be the best interface exposed by the `haproxy` class and the `haproxy::listen` and `haproxy::balancermember` types for making full use of the Augeas lens?

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
