### ISSUE TITLE
This module uses deprecated dependency (translate)

### ISSUE THREAD

**Issue by morsik** [puppetlabs/puppetlabs-haproxy#622]
## Describe the Bug
When I tried to use this module, I went into issue:

```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Unknown function: 'translate'. (file: /etc/puppet/code/environments/haproxy_lb/modules/concat/manifests/fragment.pp, line: 27, column: 10) (file: /etc/puppet/code/environments/haproxy_lb/modules/haproxy/manifests/frontend.pp, line: 160) on node lb-1
```

## Expected Behavior
Should work.

## Steps to Reproduce
Just follow basic docs.

## What I found

According to [this documentation](https://forge.puppet.com/modules/puppetlabs/translate/readme) this module is deprecated, so use of it should be removed from this haproxy module.

**Comment by kenyon** [comment]
This module doesn't use translate. Your error is coming from the concat module, but concat also doesn't use translate since a long time ago: https://github.com/puppetlabs/puppetlabs-concat/commit/a1a33469b73e72deccbff779ba3c711005f2bfe4

So you must be using an old version of concat.

**Comment by morsik** [comment]
@kenyon Apparently you're right! We have stick to some old commit in our `Puppetfile`. Thanks, and orry for problem! I'm still learning Pupppet after years of Salt ;)

Will fix on our side.
