### ISSUE TITLE
haproxy package doesn't exist on Debian Stable (wheezy)

### ISSUE THREAD

**Issue by juasiepo** [puppetlabs/puppetlabs-haproxy#63]
So it is necessary to  add the wheezy-backports repository to make the haproxy class work

 apt::source { 'wheezy-backports':
    location => 'http://ftp.debian.org/debian',
    release  => 'wheezy-backports',
    repos    => 'main ',
    before   => Class['haproxy'],
 }

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
